#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running..."

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VCS_REF=$(git rev-parse --short HEAD)

echo "BUILD_DATE: ${BUILD_DATE}"
echo "VCS_REF: ${VCS_REF}"

printenv

docker buildx create --use

docker buildx ls

docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 \
  --build-arg BUILD_DATE=${BUILD_DATE} \
  --build-arg VCS_REF=${VCS_REF} \
  --tag $IMAGE_NAME .
